# Generated by Django 4.2.3 on 2023-07-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
