# Generated by Django 4.2.3 on 2023-07-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0003_alter_author_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.CharField(max_length=250),
        ),
    ]
